---
### Use ansible-galaxy to install otel https://docs.splunk.com/Observability/gdi/opentelemetry/deployments/deployments-linux-ansible.html
### Requires the signalfx.splunk_otel_collector collection to be installed on the host running Ansible, and can be installed using following command:
### ansible-galaxy collection install signalfx.splunk_otel_collector

- name: Install splunk_otel_collector using ansible-galaxy signalfx.splunk_otel_collector collection
  include_role:
    name: "signalfx.splunk_otel_collector.collector"
  when: galaxy_otel == "yes"
  vars:
    splunk_access_token: '{{ access_token }}'
    splunk_realm: '{{ realm }}'
    splunk_memory_total_mib: "384"
    splunk_ballast_size_mib: "128"
    install_fluentd: false
    # splunk_otel_collector_config: /tmp/agent_config.yaml
    # splunk_otel_collector_config_source: templates/agent_config.yaml
    # splunk_otel_collector_additional_env_vars:
    #   MY_CUSTOM_VAR1: value1
    #   MY_CUSTOM_VAR2: value2
  
### Details on what parameters can be used above can be found here https://github.com/signalfx/splunk-otel-collector/tree/main/deployments/ansible/roles/collector

### If 'galaxy_otel' is set to 'no' in terraform.tfvars then rather than using the default ansible-galaxy collection for installing the otel collector
### a simpler install method will be used which can speed up deployments and removes the dependency on ansible-galaxy

## Linux Instances ##

- name: Check for existing agent
  stat:
    path: /etc/otel/collector/agent_config.yaml
  register: agent_config
  when: 
    - ansible_os_family == "Posix"
    - galaxy_otel == "no"

- name: Does agent_config.yaml exist
  debug:
    msg: "agent_config.yaml already exists"
  when: 
    - ansible_os_family == "Posix"
    - galaxy_otel == "no"
    - agent_config.stat.exists and agent_config.stat.isreg

- name: Get Splunk OTEL Agent Install Script
  ansible.builtin.get_url:
    url: https://dl.signalfx.com/splunk-otel-collector.sh 
    dest: /tmp/splunk-otel-collector.sh
  when: 
    - ansible_os_family == "Posix"
    - galaxy_otel == "no"
    - not agent_config.stat.exists

- name: Install Splunk OTEL Agent
  become: yes
  command: sh /tmp/splunk-otel-collector.sh --realm {{ realm }}  -- {{ access_token }} --mode agent --without-fluentd
  when:
    - ansible_os_family == "Posix"
    - galaxy_otel == "no"
    - not agent_config.stat.exists

## Linux Instances End ##

## Windows Instances ##

#TBC

## Windows Instances End##