# This file is managed by Ansible so should not be edited directly
# Deployed as part of the mysql role
# Merging is controlled by the OTELCOL_OPTIONS setting in /etc/otel/collector/splunk-otel-collector.conf which is also deployed via Ansible

service:
  extensions:
  - health_check
  - http_forwarder
  - zpages
  - memory_ballast
  - smartagent

  pipelines:
    traces:
      receivers: 
      - jaeger
      - otlp
      - smartagent/signalfx-forwarder
      - zipkin
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters: 
      - sapm
      - signalfx
      # Use instead when sending to gateway
      # exporters:
      # - otlp
      # - signalfx
    
    metrics/internal:
      receivers: 
      - prometheus/internal
      processors: 
      - memory_limiter
      - batch
      - resourcedetection
      # When sending to gateway, at least one metrics pipeline needs
      # to use signalfx exporter so host metadata gets emitted
      exporters: 
      - signalfx
    
    logs/signalfx:
      receivers: 
      - signalfx
      - smartagent/processlist
      processors: 
      - memory_limiter
      - batch
      - resourcedetection
      exporters: 
      - signalfx
    
    logs:
      receivers: 
      - fluentforward
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters: 
      - splunk_hec
      - splunk_hec/profiling
      # Use instead when sending to gateway
      #exporters: 
      # - otlp