service:
  telemetry:
    logs:
      encoding: json
      level: "debug"
      # output_paths: [/var/log/otel/collector.log]
      # error_output_paths: [/var/log/otel/collector.log]
      output_paths: [/mnt/logs/otel/collector.log]
      error_output_paths: [/mnt/logs/otel/collector.log]