# This file is managed by Ansible so should not be edited directly
# Deployed as part of the mysql role
# Merging is controlled by the OTELCOL_OPTIONS setting in /etc/otel/collector/splunk-otel-collector.conf which is also deployed via Ansible

service:
  extensions:
  - headers_setter
  - health_check
  - http_forwarder
  - zpages
  - smartagent

  pipelines:
    traces:
      receivers: 
      - jaeger
      - otlp
      - zipkin
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters: 
      - otlphttp
      - signalfx
      # Use instead when sending to gateway
      # exporters:
      # - otlp/gateway
      # - signalfx
    
    metrics/internal:
      receivers: 
      - prometheus/internal
      processors: 
      - memory_limiter
      - batch
      - resourcedetection
      - resource/add_mode
      exporters: 
      - signalfx
    
    logs/signalfx:
      receivers: 
      - signalfx
      - smartagent/processlist
      processors: 
      - memory_limiter
      - batch
      - resourcedetection
      exporters: 
      - signalfx

    logs/entities:
      # Receivers are dynamically added if discovery mode is enabled
      receivers: 
      - nop
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - otlphttp/entities
      # Use instead when sending to gateway
      - otlp/gateway

    logs:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      #- resource/add_environment
      exporters: 
      - splunk_hec
      - splunk_hec/profiling
      # Use instead when sending to gateway
      # - otlp/gateway